services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: restaurantemonsieur
      MYSQL_ROOT_PASSWORD: senha123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: